# prefixキーをC-qに変更する
set -g prefix C-q

# C-bのキーバインドを解除する
unbind C-b

# キーストロークのディレイを減らす
set -sg escape-time 1

# ウィンドウのインデックスを1から始める
set -g base-index 1

# ペインのインデックスを1から始める
setw -g pane-base-index 1

# 設定ファイルをリロードする
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# C-q*2でtmux内のプログラムにC-qを送る
bind C-q send-prefix

# | でペインを縦に分割する
bind | split-window -h

# - でペインを横に分割する
bind - split-window -v

# 履歴を100000件保存する
set-option -g history-limit 100000

# マウス操作を有効にする（ペイン切り替え・スクロール）
set -g mouse on

# True Color対応
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# ステータスバーのスタイル
set -g status-style 'fg=white,bg=black'

# ウィンドウリストのスタイル
setw -g window-status-style 'fg=cyan,dim'
# アクティブなウィンドウを目立たせる
setw -g window-status-current-style 'fg=white,bg=red,bright'

# ペインボーダーのスタイル
set -g pane-border-style 'fg=green,bg=black'
# アクティブなペインを目立たせる
set -g pane-active-border-style 'fg=white,bg=yellow'

# コマンドラインのスタイル
set -g message-style 'fg=white,bg=black,bright'

# 通知
## ステータスバーにテキストで通知を表示
set -g visual-bell on
## どのウィンドウのベルでも通知
set -g bell-action any
## 赤太字で強調
set -g window-status-bell-style 'fg=red,bold'

# ステータスバーを設定する
## 左パネルを設定する
set -g status-left-length 40
set -g status-left "#[fg=green]Session: #S #[fg=yellow]#I #[fg=cyan]#P"
## 右パネルを設定する
set -g status-right "#[fg=cyan][%Y-%m-%d(%a) %H:%M]"
## リフレッシュの間隔を設定する(デフォルト 15秒)
set -g status-interval 60
## ウィンドウリストの位置を中心寄せにする
set -g status-justify centre
## ヴィジュアルノーティフィケーションを有効にする
setw -g monitor-activity on
set -g visual-activity on
