[profile maru]
sso_session = maru
sso_account_id = 634337128079
sso_role_name = AdministratorAccess
region = ap-northeast-1

[sso-session maru]
sso_start_url = https://d-9567b5f790.awsapps.com/start
sso_region = ap-northeast-1
sso_registration_scopes = sso:account:access
